### ISSUE TITLE
[Feature] Docker image

### ISSUE THREAD

**Issue by ToshY** [undecaf/hetzner-snap-and-rotate#1]
In order to test out this script, I would like to have a docker image (similar as in [fbrettnich/hcloud-snapshot-as-backup](https://github.com/fbrettnich/hcloud-snapshot-as-backup)).

For this feature, it would require the following to be needed:
- `Dockerfile` - instructions for building image.
- `.github/workflows/release.yml` - for automatically building and pushing docker image to GHCR.
  -  https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
- Examples on how to run the docker container or with docker compose config (`compose.yaml`) with some basic environment variables (e.g. `API_TOKEN`) that can be used.

**Comment by undecaf** [comment]
Fixed in [this release](https://github.com/undecaf/hetzner-snap-and-rotate/releases/tag/v1.0.1)

**Comment by cirrusflyer** [comment]
Could this be enhanced to run as a docker compose with a env cron line the compose file for scheduling, similar as in fbrettnich/hcloud-snapshot-as-backup.

**Comment by undecaf** [comment]
@cirrusflyer IMHO the backup script should not be concerned with when it has to run, following the Unix philosophy of "do one thing well".
But in order to run the backup via cron in a container, one could build a new Docker image using [undecaf/hetzner-snap-and-rotate](https://hub.docker.com/r/undecaf/hetzner-snap-and-rotate) as the [base image](https://docs.docker.com/build/building/base-images/).
However, I consider this beyond the scope of this project, and I will not pursue such a solution.

**Comment by jeykodev** [comment]
@undecaf at first I thought like @cirrusflyer but after setting up a cron oneliner, I don't see the need for an cron image either. 

Thx for sharing your project @undecaf!
